# Generated by Django 3.2.9 on 2021-12-14 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211214_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankstatement',
            old_name='statement_title',
            new_name='docfile',
        ),
    ]
